FROM hbpmip/java-base-build:3.5.0-jdk-8-7

COPY pom.xml /project/pom.xml
COPY src/ /project/src
COPY docker/run-tests.sh /

RUN chmod a+rx /run-tests.sh \
    && mkdir -p /root/.RapidMiner

ENTRYPOINT ["/run-tests.sh"]
